# Generated by Django 4.2.5 on 2023-09-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedata',
            options={'verbose_name_plural': 'Employee Attendance'},
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='attendace',
            new_name='attendance',
        ),
    ]
